### PR TITLE
Added hex offsets

### PR DESCRIPTION
**Pull request by satandidnowrong**
Thanks for the information. I look forward to it being full and precise.

### CODE REVIEW

**Comment by krisives** [comment]
Sorry that this got lost in my inbox. Thank you for the help.

**Comment by satandidnowrong** [comment]
Glad to be a part. I'm working on finding how the last bits of an item are affected if the same item is socketted or not socketted. I have seen the few item format pages around, but no clue yet as to how it is decided besides manually setting it. Do you know of the algo?

**Comment by krisives** [comment]
Let's make a new issue for that and maybe you can attach some files? Basically just make a character with some known items (and preferably nothing else) and we can discover what it is.

**Comment by krisives** [comment]
Or read https://github.com/squeek502/d2itemreader

**Pull request merged**
